src/A4_Project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.urls import path
from .views import post_list_and_create
from .views import load_post_data_view
from .views import like_unlike_post
from .views import post_detail_data_view
from .views import post_detail
from .views import delete_post
from .views import update_post
from .views import image_upload_view



app_name = 'posts'

urlpatterns = [
    path('', post_list_and_create, name='main-board'),
    path('like-unlike/', like_unlike_post, name='like-unlike'),
    path('upload/', image_upload_view, name='image-upload'),
    path('<pk>', post_detail, name='post-detail'),
    path('<pk>/update/', update_post, name='post-update'),
    path('<pk>/delete/', delete_post, name='post-delete'),

    path('data/<int:num_posts>/', load_post_data_view, name='posts-data'),
    path('<pk>/data/', post_detail_data_view, name='post-detail-data'),
]

src/profiles/urls.py
from django.urls import path
from .views import my_profile_view
app_name = 'profiles'

urlpatterns = [
    path('my/', my_profile_view, name='my-profile-view')
]

src/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    liked = models.ManyToManyField(User, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str (self.title)

    @property
    def like_count(self):
        return self.liked.all().count()
    
    def get_photos(self):
        return self.photo_set.all()

    class Meta:
        ordering = ("-created",)

class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="photos")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post.title}-{self.pk}"

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(default='avatar.jpg', upload_to='avatars')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"profile of the user {self.user.username}"

src/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    #title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
   #body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
    class Meta:
        model = Post
        fields = ('title', 'body',)

src/profiles/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'avatar',)

src/posts/views.py
from django.shortcuts import render
from .models import Post
from .models import Photo
from django.http import JsonResponse
from django.http import HttpResponse
from .forms import PostForm
from profiles.models import Profile
from .utils import action_permission
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def post_list_and_create(request):
    form  = PostForm(request.POST or None)
    #qs = Post.objects.all()

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        if form.is_valid():
            author = Profile.objects.get(user=request.user)
            instance = form.save(commit=False)
            instance.author = author
            instance.save()
            return JsonResponse({
                'title': instance.title,
                'body': instance.body,
                'author': instance.author.user.username,
                'id': instance.id,
            })
    context = {
        'form' : form,

    }

    return render(request, 'posts/main.html', context)

@login_required
def post_detail(request, pk):
    obj = Post.objects.get(pk=pk)
    form = PostForm()

    context = {
        'obj' : obj,
        'form' : form,
    }

    return render(request, 'posts/detail.html', context)

def load_post_data_view(request, num_posts):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        sort_method = request.GET.get('sort')
        visible = 3
        upper = num_posts
        lower = upper - visible
        size = Post.objects.all().count()

        if sort_method == 'alphabetical':
            qs = Post.objects.all().order_by('title')
        elif sort_method == 'oldest':
            qs = Post.objects.all().order_by('id')
        else:  # newest
            qs = Post.objects.all().order_by('-id')

        data =[]
        for obj in qs:
            item ={
            'id': obj.id,
            'title': obj.title,
            'body': obj.body,
            'liked' : True if request.user in obj.liked.all() else False,
            'count' : obj.like_count,
            'author': obj.author.user.username
            }
            data.append(item)
        return JsonResponse({'data':data[lower:upper], 'size':size})

def post_detail_data_view(request, pk):
    obj = Post.objects.get(pk=pk)
    data = {
        'id': obj.id,
        'title': obj.title,
        'body': obj.body,
        'author': obj.author.user.username,
        'logged_in' : request.user.username,
    }
    return JsonResponse({'data': data})


def like_unlike_post(request):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        pk = request.POST.get('pk')
        obj = Post.objects.get(pk=pk)

        if request.user in obj.liked.all():
            liked = False
            obj.liked.remove(request.user)
        else:
            liked = True
            obj.liked.add(request.user)

        return JsonResponse({'liked': liked, 'count': obj.like_count})

@action_permission
def update_post(request, pk):
    obj = Post.objects.get(pk=pk)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        new_title = request.POST.get('title')
        new_body = request.POST.get('body')
        obj.title = new_title
        obj.body = new_body
        obj.save()
    return JsonResponse({
        'title': new_title,
        'body' : new_body,
    })

@action_permission
def delete_post(request, pk):
    obj = Post.objects.get(pk=pk)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        obj.delete()
    return JsonResponse({})

def image_upload_view(request):
    #print(request.FILES)
    if request.method == 'POST':
        img = request.FILES.get('file')
        new_post_id = request.POST.get('new_post_id')
        post = Post.objects.get(id=new_post_id)
        Photo.objects.create(image=img, post=post)
    return HttpResponse("Upload successful", status=200)

src/profiles/views.py
from django.shortcuts import render
from .models import Profile
from .forms import ProfileForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

def my_profile_view(request):
    obj = Profile.objects.get(user=request.user)
    form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        if form.is_valid():
            instance = form.save()
            return JsonResponse({
                'bio': instance.bio,
                'avatar': instance.avatar.url,
                'user': instance.user.username
            })
    context = {
         'obj': obj,
        'form': form,
    }

    return render(request, 'profiles/main.html', context)

src/posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'posts/detail.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.title}} detail
{% endblock title %}

{% block content %}
    <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Update post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="alert-box"></div>
                <form id="update-form">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
                        <button type="submit" class="btn btn-success">update</button>
                     </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Delete post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete<b>"{{obj.title}}"</b>?
            </div>
                <div class="modal-footer">
                    <form id="delete-form">
                        {% csrf_token %}
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
                            <button type="submit" class="btn btn-success">delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!--Carousel-->
    {% if obj.get_photos %}
        <div id="carouselExample" class="carousel slide mb-2" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for p in obj.get_photos %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <img src="{{p.image.url}}" class="d-block w-100" alt="photo {{obj.pk}}">
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    {% else %}
        <div class="mt-2 mb-2"> No photos to show</div>
    {% endif %}


    <a href="{% url 'posts:main-board' %}" id="back-btn" class="btn btn-info">back</a>
    <button id="update-btn" class="btn btn-primary not-visible" data-bs-toggle="modal" data-bs-target="#updateModal">update</button>
    <button id="delete-btn" class="btn btn-danger not-visible" data-bs-toggle="modal" data-bs-target="#deleteModal">delete</button>
    <div id="spinner-box" class="text-center">
    <div class="spinner-border not-visible" role="status"></div>
    </div>
    <div class="mt-1" id="post-box"></div>
{% endblock content %}

src/posts/templates/posts/main.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'posts/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
posts   
{% endblock title %}

{% block content %}    
    <!-- Modal -->
    <div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Create post</h1>
                    <button type="submit" class="btn-close add-modal-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="post-form">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger add-modal-close" data-bs-dismiss="modal">close</button>
                            <button type="submit" id="add-btn" class="btn btn-success">+ add</button>
                        </div>
                    </form>
                    <form action="upload/" id="my-dropzone" class="dropzone dz not-visible">
                        {% csrf_token %}
                        <div class="fallback">
                            <input name="file" type="file" multiple/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    
    <div class="d-flex justify-content-end align-items-center mb-3 gap-2">
        <label for="sort-select" class="form-label mb-0">Sort posts by:</label>
        <select id="sort-select" class="form-select form-select-sm w-auto">
          <option value="newest" selected>Newest</option>
          <option value="oldest">Oldest</option>
          <option value="alphabetical">Alphabetical</option>
        </select>
      </div>
      <button type="button" class="btn btn-success mb-2" data-bs-toggle="modal" data-bs-target="#addPostModal">
        + Add Post
      </button>
    <div id="posts-box"></div>
    <div id="alert-box"></div>

    <div id="posts-box"></div>
    <div id="spinner-box"class="text-center">
        <div class="spinner-border" role="status"></div>
    </div>
    <div class="text-center mb-3" id="end-box"></div>
    <button class="btm btn-primary" id="load-btn">Load more</button>
{% endblock content %}

src/profiles/templates/profiles/main.html
{% extends "base.html" %}
{% load static %}

{% load crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'profiles/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
My Profile  
{% endblock title %}

{% block content %}
    <div id="alert-box"></div>
    <h3>{{obj.user}}</h3>
    <hr>
    <div class="text-center" id="avatar-box">
        <img src="{{obj.avatar.url}}" class="rounded" height="200px" width="auto" alt="{{obj.user.username}}">
    </div>
    <form id="profile-form">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-primary mt-3">save</button>
    </form>
{% endblock content %}

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <!-- Dropzone CSS -->
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css">

    <!-- Dropzone JS -->
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>

    <!-- Custom js -->
    <script src="{% static 'functions.js' %}" defer></script>
    {% block scripts %}
    {% endblock scripts %}

    <title>read posts | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </body>
</html>

src/templates/navbar.html
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold" href="{% url 'posts:main-board' %}">A4</a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'posts:main-board' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'profiles:my-profile-view' %}">My Profile</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  